services:
  netbox:
    image: netboxcommunity/netbox:latest
    ports:
      - "127.0.0.1:8000:8080"
    environment:
      DB_NAME: netbox
      DB_USER: netbox
      DB_PASSWORD: netbox
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: netbox
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD: netbox
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
